# https://github.com/compose-spec/compose-spec/blob/master/spec.md

###################
# Services
###################

services:
  ###################
  # PostgreSQL
  ###################
  db-postgres:
    container_name: ${PG_CONTAINER_NAME}
    image: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      # - ./volumes/sql:/docker-entrypoint-initdb.d
      # - ./volumes/Makefile:/Makefile
      # - ./volumes/.env:/.env
      # - ./volumes/sql:/sql
    networks:
      - net-bp
    ports:
      - ${PORT_POSTGRES}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB=${POSTGRES_DB}
    restart: on-failure # always
    
  ###################
  # pgAdmin
  ###################
  db-pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4
    # volumes:
    # - ./volumes/pgadmin:/var/lib/pgadmin
    networks:
      - net-bp
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PORT_PGADMIN}:80

networks:
  net-bp:
    # network name
    driver: bridge
